name: code_coverage

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Code coverage
        uses: qltysh/qlty-action/coverage@main
        with:
          coverage-token: {{secrets.QLTY_COVERAGE_TOKEN}}
          files: coverage/lcov.info